### PR TITLE
The new build

### LINKED ISSUE #46: Sorry to tell everyone but I currently won't maintain this repo anymore
@nedrichards @TingPing @barthalion @alexlarsson @ebassi @jurf 

I have recently graduated from campus and found a job, and I don't have much spare time as before. Missing my school days. 

This repo consists of a Python script generating a JSON recipe. Though not fully documented, the symbol names should be pretty self-explanatory. 

Feel free to ask me about any further questions about it. I will check my GitHub inbox irregularly. 

Wishing volunteers for our project and our dream for free softwares!

### PR DESCRIPTION
**Pull request by gasinvein**
Differences from previous flatpak recepies:
- `flatpak-node-generator.py` with several changes (patches pending) is used to generate sources for yarn packages and things they download
- Added wrapper script, derived from VS Code flatpak (the proprietary one)
  - Node.js, Python and Cargo packages are isolated from the host
  - SDK extensions are enabled automatically if set in `FLATPAK_ENABLE_SDK_EXT` env var
- Tools extensions from VS Code flatpak are reused
- VS Code is patched to put IPC sockets in a directory shared between instances, so opening files in existing window (flathub/com.visualstudio.code#75) works now
  - Live Share should work as well given its external dependencies (krb5, openssl 1.0 and xprop) are satisfied
- Builtin marketplace extensions are disabled for now; until bundled, they can be installed manually from marketplace

Closes #46 

Todo:
- [x] Automate appstream releases generation
- [ ] Pre-download specified versions of node-headers
- [ ] Bundle marketplace extensions (or not)

NB: This build is affected by flathub/com.visualstudio.code#159 (may freeze on launch or workspace switch), cause unknown yet, help wanted.

### CODE REVIEW

**Comment by gasinvein** [comment]
Did anyone test this? @TingPing maybe?
I'd like to know if there are any problems besides flathub/com.visualstudio.code#159 before merging it.

**Comment by tim77** [comment]
LGTM. Please, update.

**Comment by Unrud** [comment]
The settings `telemetry.enableTelemetry` and `telemetry.enableCrashReporter` are not disabled by default.
Maybe also set `update.mode` to `none` because automatic updates are pointless for this package.

**Comment by gasinvein** [comment]
@Unrud I guess updates don't work in unofficial builds regardless of settings.

**Comment by Unrud** [comment]
> I guess updates don't work in unofficial builds regardless of settings.

You are right, the `Check for Updates...` button is missing even if it's enabled. Then you can ignore my comment.

**Comment by eternal-sorrow** [comment]
>Then you can ignore my comment.

There's still telemetry though.

**Comment by gasinvein** [comment]
@eternal-sorrow Does it work in unofficial builds either?

**Comment by eternal-sorrow** [comment]
Why wouldn't it work?

**Comment by gasinvein** [comment]
It's probably not useful for MS since the build may be altered in arbitrary way.
Anyway, I don't see where/how current build changes telemetry settings.

**Comment by mzabaluev** [comment]
While you are at it, can we deconflict the apps with `com.visualstudio.code` by not making them share the ID prefix? I've had some strangeness occur in GNOME Software, it looked like the OSS app masked out updates available for `com.visualstudio.code`, or something to that effect.

**Comment by mzabaluev** [comment]
> While you are at it, can we deconflict the apps with `com.visualstudio.code` by not making them share the ID prefix?

`io.github.microsoft.VSCode` would seem acceptable accordingly to [the conventions](https://docs.flatpak.org/en/latest/conventions.html#application-ids) and clearly indicate this app as derived from open source. Or perhaps `org.flathub.app.microsoft.VSCode` because control issues.

**Comment by eternal-sorrow** [comment]
>It's probably not useful for MS since the build may be altered in arbitrary way.

It's more about "peace of mind" that not a single byte of data is sent to MS servers. So, I, personally, would like to have these options disabled by default.

**Comment by mzabaluev** [comment]
> It's more about "peace of mind" that not a single byte of data is sent to MS servers.

Since they are the main contributor to the OSS codebase and they are fine with telemetry being used by derived projects, I don't think it is an issue _for Microsoft_. As for telemetry being enabled by default, I don't have a strong opinion. Maybe disable sending any information that might be personally identifying?

**Comment by eternal-sorrow** [comment]
>I don't think it is an issue for Microsoft

I never said that. It's an issue for me. I'd even prefer the code related to telemetry removed from the codebase completely.

**Comment by gasinvein** [comment]
@mzabaluev 
> While you are at it, can we deconflict the apps with `com.visualstudio.code` by not making them share the ID prefix? I've had some strangeness occur in GNOME Software, it looked like the OSS app masked out updates available for `com.visualstudio.code`, or something to that effect.

Tell it to @TingPing. I've already [asked](https://github.com/flathub/com.visualstudio.code.oss/issues/46#issuecomment-636366470) to change ID.

**Comment by gasinvein** [comment]
Closing in favor of flathub/flathub#1596

**Pull request closed without merging**
