### PR TITLE
Update to 18.08 runtime

### PR DESCRIPTION
**Pull request by csoriano1618**

### CODE REVIEW

**Comment by csoriano1618** [comment]
master is broken too, seems commits were made without CI passing?

**Comment by amtlib-dot-dll** [comment]
Thanks for your contribution, the `.travis.yml` file is to automatically generate `com.visualstudio.code.oss.json` from `build.py`. The recipe also tried to bundle some Python tools in a separate extension, and it looks for tools under Python 3.5.2 rather than 3.7 in the 18.08 runtime. You can modify and set up your own account in Travis to generate the JSON recipe file.

**Comment by amtlib-dot-dll** [comment]
Perhaps you can have a look at #23

**Comment by csoriano1618** [comment]
This is quite cryptic and complex to do simple modifications tbh...

**Comment by nedrichards** [comment]
We already use 18.08

**Pull request closed without merging**
